version: '3.5'

volumes: 
  grafana_data: 
services:
     push-stats:
          build: .
          restart: unless-stopped
     relay:
          image: openmetric/carbon-c-relay:latest
          volumes:
               - ./conf/relay.conf:/openmetric/conf/relay.conf:ro
          depends_on:
               - carbon
          ports:
               - '2003:2003'
          healthcheck:
               test: nc -zv localhost 2003
               interval: 10s
               timeout: 1s
               retries: 3
     carbon:
          image: openmetric/go-carbon:latest
          volumes:
               - ./conf/carbon.conf:/openmetric/conf/carbon.conf:ro
               - ./conf/schemas.conf:/openmetric/conf/schemas.conf:ro
               - ./whisper:/openmetric/data/whisper
          healthcheck:
               test: "curl -fsSL -o /dev/null 'http://localhost:8080/metrics/find/?query=*&format=json'"
               interval: 10s
               timeout: 1s
               retries: 3
     api:
          image: openmetric/carbonapi:latest
          volumes:
               - ./conf/api.yaml:/openmetric/conf/api.yaml:ro
          depends_on:
               - relay
          healthcheck:
               test: 'curl -fsSL -o /dev/null http://localhost:8080/lb_check'
               interval: 10s
               timeout: 1s
               retries: 3
     grafana:
          image: grafana/grafana-enterprise:9.0.4-ubuntu
          volumes:
               - grafana_data:/var/lib/grafana
          ports:
               - '${GF_SERVER_HTTP_PORT}:${GF_SERVER_HTTP_PORT}'
          depends_on:
               - relay
          env_file:
               - ./conf/grafana.env
          healthcheck:
               test: 'curl -fsSL -o /dev/null http://localhost:${GF_SERVER_HTTP_PORT}/login'
               interval: 10s
               timeout: 1s
               retries: 3
